[package]
name = "faucon"
version = "0.1.0"
authors = ["Valentin B. <valentin.be@protonmail.com>"]
description = "NVIDIA Falcon CPU emulator"
license = "Apache-2.0/MIT"
readme = "README.md"
homepage = "https://github.com/vbe0201/faucon"
edition = "2018"

[workspace]
members = ["faucon-asm", "faucon-asm-derive"]

[dependencies]
faucon-asm = { path = "faucon-asm" }
