# The default configuration.
# See CONFIGURATION.md for more information

[falcon]
version = 5
imem_size = 0x80
dmem_size = 0x4000
clock_freq = 700.123456

[falcon.dma]
ports = [
    { index = 0, start_addr = 0xDEADBEEF, size = 0x10 },
    { index = 7, start_addr = 0xF00DBABE, size = 0x50 },
]

[ptimer]
periodic_freq = 772.021912
watchdog_freq = 772.081543
