[package]
name = "faucon-asm"
version = "0.1.0"
authors = ["Valentin B. <valentin.be@protonmail.com>"]
description = "A crate for working with the NVIDIA Falcon ISA."
license = "Apache-2.0/MIT"
homepage = "https://github.com/vbe0201/faucon"
edition = "2018"

[[bin]]
name = "fasm"
path = "src/main.rs"

[dependencies]
faucon-asm-derive = { path = "../faucon-asm-derive" }
